### ISSUE TITLE
test_in_out_var

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/EstimationPy#5]
Running ``estimationpy/tests/test_in_out_var.py`` results in:

```
======================================================================
ERROR: test_get_data_series_from_csv (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_in_out_var.py", line 117, in test_get_data_series_from_csv
    reader.open_csv(self.csvOK)
  File "/home/dhbubu/git/estimationpy/EstimationPy/estimationpy/fmu_utils/csv_reader.py", line 163, in open_csv
    df = self.__open_csv__(filename)
  File "/home/dhbubu/git/estimationpy/EstimationPy/estimationpy/fmu_utils/csv_reader.py", line 123, in __open_csv__
    df.sort(inplace = True)
  File "/home/dhbubu/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 3614, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'

----------------------------------------------------------------------
Ran 8 tests in 0.016s

FAILED (errors=1)
```

**Comment by dhblum** [comment]
Closed by https://github.com/lbl-srg/EstimationPy/pull/3.
